version: '3'

services:
  client:
    build: ./client
    ports: 
      - "5173:5173"
    depends_on:
      - api01
    networks:
      - BOOT
      
  api: &api
    build: ./server
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    depends_on:
      - database
    networks:
      - BOOT

  api01:
    <<: *api
    ports:
      - "3333:3333"
    command: sh -c "sleep 10 && npx prisma migrate deploy"

  api02:
    <<: *api
    ports:
      - "3334:3333"

  api03:
    <<: *api
    ports:
      - "3335:3333"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api02
      - api03
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
    ports:
      - "9999:9999"
    networks:
      - BOOT

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123pass
      MYSQL_DATABASE: bootdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 123pass
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - BOOT

networks:
  BOOT: